// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxiyjvtqgvbvcscbxxnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aXlqdnRxZ3ZidmNzY2J4eG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxOTcxNjAsImV4cCI6MjA4MTc3MzE2MH0.03PrYEvv8xUUM-UVge_S4Kapo6RUBYkk5W0XPcxRg68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});